<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>osu-vrc-chatbox</AssemblyName>
    <RootNamespace>OsuVrcChatbox.ConsoleApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OsuVrcChatbox.Core\OsuVrcChatbox.Core.csproj" />
  </ItemGroup>

</Project>
